### ISSUE TITLE
keybindings.sh is out-of-sync with sxhkdrc/sxhkdrc-minimal

### ISSUE THREAD

**Issue by carmelowoodgett** [Chrysostomus/bspwm-scripts#11]
keybindings.sh:
`Super + shift + r             |- Reload bspwms configuration file
`

sxhkdrc/sxhkdrc:
```
# In case bspwmrc fails to execute/you wish have plugged in a new monitor
super + shift + r
	bspwmrc
```

I just started trying this edition out and for a good 5 minutes I thought I was crazy :stuck_out_tongue:

**Comment by Chrysostomus** [comment]
I don't understand the issue? Does keybinding not execute ~/.config/bspwm/bspwmrc? Is it not the $PATH or something?

**Comment by carmelowoodgett** [comment]
Hmm, maybe I'm reading it wrong. So, "Reload bspwms configuration file" makes me think that it reloads bspwm from the configuration, such as when you make changes to the config and want to see those reflected. However, `bspwmrc` opens the config in a text editor.

Sorry, I'm being pedantic, lol.
