### ISSUE TITLE
Add focusmover to bspwm-scripts

### ISSUE THREAD

**Issue by Doaxan** [Chrysostomus/bspwm-scripts#2]
Please add **focusmover** to bspwm-scripts.

**Comment by Chrysostomus** [comment]
It is part of the package limepanel.

**Comment by Doaxan** [comment]
It would be better to move or copy it to the bspwm-scripts package, because users do not use limepanel will not work with focus change with sxhkdrc.

**Comment by Vrakfall** [comment]
It actually seems to be a dependency of both packages. Maybe it could be included as a submodule of both repos.

**Comment by Chrysostomus** [comment]
Can't put in both, because it would cause files in packages to conflict. But yeah, it should probably be moved to bspwm-scripts and limepanel dependency removed...

**Comment by Vrakfall** [comment]
I don't think a submodule would conflict.

**Comment by Chrysostomus** [comment]
Ok, I'm not familiar with the term so I may have misunderstood. What do you mean by a submodule?

**Comment by Vrakfall** [comment]
It's a repo as a dependency inside another repo, the former being a directory in the latter. (See also [this][1])

You could make a repo with only that one file, `focusmover`, and make it a submodule inside `bspwm-scripts` and `limepanel`. (You can also add a symlink so it's still in the bin file, or not. That might actually make some file conflicts; I don't know how you merge your 2 repos together.)

Here's an [example from my dotfiles][3] using [`dotbot`][2] as a dependency (this is a work in progress, don't look at it too close).

[1]: https://git-scm.com/book/en/v2/Git-Tools-Submodules "Git Submodules"
[2]: https://github.com/anishathalye/dotbot "anishathalye/dotbot"
[3]: https://github.com/Vrakfall/dotfiles "Vrakfall/dotfiles"

**Comment by Vrakfall** [comment]
Ahem, forget the symlinks, I've seen everything is sent to `/usr/bin`.
Well, maybe you can also move `focusmover` over here and make `bspwm-scripts` a build dependency of `limepanel`.
