### ISSUE TITLE
Some scripts use old bspwm syntax

### ISSUE THREAD

**Issue by kainonergon** [Chrysostomus/bspwm-scripts#4]
Syntax changes:
- `-W|--windows, -w|--window, -w|--to-window` are now `-N|--nodes, -n|--node, -n|--to-node`
- `-t floating=off` and `-t floating=on` are now `-t tiled` and `-t floating`

Scripts that need correction:

- [bspcp](https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/bspcp)
- [swapOrMoveIn.sh](https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/swapOrMoveIn.sh)

**Comment by Chrysostomus** [comment]
Thanks! I had thought I had migrated everything, but it seems I missed some.

**Comment by Chrysostomus** [comment]
Okay, fixed those two, but found that window-placer issues broken still...

**Comment by Chrysostomus** [comment]
Fixed, sort of...
