### ISSUE TITLE
terminal transparency

### ISSUE THREAD

**Issue by bgdaniels** [Chrysostomus/bspwm-scripts#5]
BTW, best release so far! I have googled until I am tired of googling :-) but can not find out how to get transparency in zsh or tmux. Can it be done?
thanks

**Comment by Chrysostomus** [comment]
Which terminal? Doesn't work with st, works with urxvt and many others.

**Comment by bgdaniels** [comment]
thanks for the reply. I am using the default terminal. I thought it was tmux? The ps -p$PPID says tmux.

**Comment by Chrysostomus** [comment]
Tmux is the terminal multiplexer. Sterminal (the default) is patched st+tmux.

**Comment by bgdaniels** [comment]
okay thanks! now your previous comment makes sense to me ;-)
